language: python
python:
  - '3.9'

addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10-postgis-2.4

before_script:
  - pip install -r requirements.txt
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz
  - tar -zxvf geckodriver-v0.29.1-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin
  - psql -U postgres -c "create extension postgis"
  - psql -c 'create database sele_db;' -U postgres
  # - wget https://download.osgeo.org/gdal/3.4.0/gdal-3.4.0.tar.gz
  # - tar -zxvf gdal-3.4.0.tar.gz
  # - cd gdal-3.4.0
  - ls
  - cd ..
  - pwd
  - ls
  - cd ..
  - pwd
  - ls
  - cd ..
  - pwd
  - ls
  - cd ..
  - pwd
  - ls
 

  # - pip install /home/travis/build/ThomasPiergiovanni/sele/config/settings/GDAL-3.4.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl 


env: DJANGO_SETTINGS_MODULE="config.settings.travis"

script:
  - python manage.py test

branches:
  only:
    - staging