# Generated by Django 4.0 on 2022-01-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
