# Generated by Django 4.0 on 2022-01-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
