# Generated by Django 4.0 on 2022-01-31 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_email_alter_customuser_user_name'),
        ('proposition', '0007_creatortype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1000)),
                ('creation_date', models.DateTimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposition.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser')),
                ('creator_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposition.creatortype')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposition.domain')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposition.kind')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposition.rating')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposition.status')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser')),
            ],
        ),
    ]
