# Generated by Django 4.0 on 2022-01-31 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_email_alter_customuser_user_name'),
        ('proposition', '0008_proposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='authentication.customuser'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='taker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taker', to='authentication.customuser'),
        ),
    ]
