# Generated by Django 4.0 on 2022-02-01 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_email_alter_customuser_user_name'),
        ('proposition', '0009_alter_proposition_creator_alter_proposition_taker'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser')),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposition.proposition')),
            ],
        ),
    ]
