# Generated by Django 4.0 on 2022-02-01 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_alter_customuser_email_alter_customuser_user_name'),
        ('proposition', '0010_blockedtaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='relation_custom_user',
            field=models.ManyToManyField(related_name='relation_custom_user', through='proposition.BlockedTaker', to=settings.AUTH_USER_MODEL),
        ),
    ]
