# Generated by Django 4.0 on 2022-03-28 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0012_remove_proposition_relation_custom_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='category',
        ),
        migrations.AddField(
            model_name='proposition',
            name='proposition_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proposition_category', to='proposition.category'),
            preserve_default=False,
        ),
    ]
