# Generated by Django 4.0 on 2022-03-28 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_collectivity'),
        ('proposition', '0013_remove_proposition_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='creator',
        ),
        migrations.AddField(
            model_name='proposition',
            name='proposition_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proposition_creator', to='authentication.customuser'),
            preserve_default=False,
        ),
    ]
