# Generated by Django 4.0 on 2022-03-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0015_remove_proposition_creator_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='domain',
        ),
        migrations.AddField(
            model_name='proposition',
            name='proposition_domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proposition_domain', to='proposition.domain'),
            preserve_default=False,
        ),
    ]
