# Generated by Django 4.0 on 2022-03-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_collectivity'),
        ('proposition', '0018_alter_proposition_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedtaker',
            name='custom_user',
        ),
        migrations.RemoveField(
            model_name='blockedtaker',
            name='proposition',
        ),
        migrations.AddField(
            model_name='blockedtaker',
            name='blocked_taker_custom_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_taker_custom_user', to='authentication.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockedtaker',
            name='blocked_taker_proposition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_taker_custom_user', to='proposition.proposition'),
            preserve_default=False,
        ),
    ]
