# Generated by Django 4.0 on 2022-03-29 18:45

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0019_remove_blockedtaker_custom_user_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proposition',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', django.db.models.expressions.F('end_date'))), name='start_data_lte_end_date'),
        ),
    ]
