# Generated by Django 4.0 on 2022-03-31 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0020_proposition_start_data_lte_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedtaker',
            name='blocked_taker_proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_taker_proposition', to='proposition.proposition'),
        ),
    ]
