# Generated by Django 4.0 on 2022-03-31 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_customuser_collectivity'),
        ('proposition', '0021_alter_blockedtaker_blocked_taker_proposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedtaker',
            name='blocked_taker_custom_user',
        ),
        migrations.RemoveField(
            model_name='blockedtaker',
            name='blocked_taker_proposition',
        ),
        migrations.AlterField(
            model_name='proposition',
            name='blocked_takers',
            field=models.ManyToManyField(related_name='blocked_takers', through='BlockedTaker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BlockedTaker',
        ),
    ]
