# Generated by Django 4.0 on 2022-03-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0022_remove_blockedtaker_blocked_taker_custom_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='blocked_takers',
        ),
    ]
