# Generated by Django 4.0 on 2022-04-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0023_remove_proposition_blocked_takers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='proposition_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposition_rating', to='proposition.rating'),
        ),
    ]
