# Generated by Django 4.0 on 2022-04-09 13:38

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0024_alter_proposition_proposition_rating'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proposition',
            constraint=models.CheckConstraint(check=models.Q(('proposition_creator', django.db.models.expressions.F('proposition_taker')), _negated=True), name='creator_not_taker'),
        ),
    ]
