# Generated by Django 4.0 on 2022-04-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_discussiontype_discussion_discussion_discussion_type'),
        ('proposition', '0026_proposition_proposition_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='proposition_discussion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proposition_discussion', to='chat.discussion'),
            preserve_default=False,
        ),
    ]
