# Generated by Django 4.0 on 2022-03-12 16:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_alter_customuser_collectivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField()),
                ('creation_date', models.DateTimeField()),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='VotingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3, unique=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=1000)),
                ('creation_date', models.DateField()),
                ('opening_date', models.DateField()),
                ('closure_date', models.DateField()),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to='authentication.customuser')),
                ('relation_vote', models.ManyToManyField(related_name='relation_vote', through='vote.Vote', to=settings.AUTH_USER_MODEL)),
                ('voting_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_method', to='vote.votingmethod')),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.voting'),
        ),
    ]
