# Generated by Django 4.0 on 2022-01-29 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VotingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3, unique=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
    ]
