# Generated by Django 4.0 on 2022-01-29 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1000)),
                ('creation_date', models.DateField()),
                ('opening_date', models.DateField()),
                ('closure_date', models.DateField()),
                ('voting_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.votingmethod')),
            ],
        ),
    ]
