# Generated by Django 4.0 on 2022-01-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_voting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
