# Generated by Django 4.0 on 2022-01-31 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_email_alter_customuser_user_name'),
        ('vote', '0003_alter_voting_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField()),
                ('creation_date', models.DateTimeField()),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.voting')),
            ],
        ),
    ]
