# Generated by Django 4.0 on 2022-01-30 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_alter_customuser_email_alter_customuser_user_name'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='custom_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to='authentication.customuser'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='relation_custom_user',
            field=models.ManyToManyField(related_name='relation_custom_user', through='chat.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
