# Generated by Django 4.0 on 2022-03-17 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_customuser_collectivity'),
        ('chat', '0002_alter_discussion_custom_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='custom_user',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='relation_custom_user',
        ),
        migrations.AddField(
            model_name='discussion',
            name='comments',
            field=models.ManyToManyField(related_name='comments', through='chat.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='discussion_custom_user',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_custom_user', to='authentication.customuser'),
            preserve_default=False,
        ),
    ]
