# Generated by Django 4.0 on 2022-04-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_discussion_custom_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
