# Generated by Django 4.0 on 2022-04-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_collectivity'),
        ('chat', '0004_alter_discussion_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='custom_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_custom_user', to='authentication.customuser'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_custom_user', to='chat.discussion'),
        ),
    ]
