# Generated by Django 4.0 on 2022-04-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_comment_custom_user_alter_comment_discussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='custom_user',
            new_name='comment_custom_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='discussion',
            new_name='comment_discussion',
        ),
    ]
