# Generated by Django 4.0 on 2021-12-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.TextField(max_length=100, verbose_name='username'),
        ),
    ]
