# Generated by Django 4.0 on 2022-01-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectivity', '0007_postalcode_collectivity'),
        ('authentication', '0003_customuser_balance_customuser_collectivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='collectivity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectivity.collectivity'),
        ),
    ]
