# Generated by Django 4.0 on 2022-05-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='custom_user',
        ),
    ]
