# Generated by Django 4.0 on 2022-01-29 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectivity', '0003_remove_postalcode_insee_code_postalcode_collectivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalcode',
            name='collectivity',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to='collectivity.collectivity'),
        ),
    ]
