# Generated by Django 4.0 on 2022-01-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectivity', '0005_alter_postalcode_collectivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postalcode',
            name='collectivity',
        ),
    ]
