# Generated by Django 4.0 on 2022-01-29 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectivity', '0006_remove_postalcode_collectivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalcode',
            name='collectivity',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, to='collectivity.collectivity'),
        ),
    ]
