# Generated by Django 4.0 on 2022-02-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectivity', '0007_postalcode_collectivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postalcode',
            name='collectivity',
        ),
        migrations.AddField(
            model_name='collectivity',
            name='postal_code',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, to='collectivity.postalcode'),
        ),
    ]
