# Generated by Django 4.0 on 2022-02-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectivity', '0008_remove_postalcode_collectivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalcode',
            name='insee_code',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
