# Generated by Django 4.0 on 2022-02-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectivity', '0009_postalcode_insee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectivity',
            name='postal_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collectivity.postalcode'),
        ),
    ]
