# Generated by Django 4.0 on 2022-02-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectivity', '0010_alter_collectivity_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectivity',
            name='postal_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectivity.postalcode'),
        ),
    ]
