# Generated by Django 4.0 on 2022-02-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectivity', '0011_alter_collectivity_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectivity',
            name='activity',
            field=models.CharField(max_length=4, verbose_name='Groupe actif'),
        ),
    ]
