# Generated by Django 4.0 on 2022-02-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectivity', '0012_alter_collectivity_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectivity',
            name='activity',
            field=models.CharField(max_length=3, verbose_name='Groupe actif'),
        ),
    ]
